SRCH-3047 update the ASIS README to use search-services
GSA/asis pull request #151
Opened 2022-06-24 16:49 UTC by krbhavith

## Summary
- Updates to README
- delete docker-compose.yml
- gem version bumps
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review:
 
#### Functionality Checks
 
- [ ] Code is functional, as tested locally.

- [ ] Tests have been added or updated to cover the proposed changes. If not, please explain why tests aren't needed:
 
- [ ] Automated checks pass, if applicable. If CodeClimate checks do not pass, explain reason for failures:
 
- [ ] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock.

- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [ ] Your target branch is `main` or `production`, or you have specified the reason for an alternate branch here:
 
- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] You have squashed your commits into a single commit (exceptions: your PR includes commits with formatting-only changes, such as required by Rubocop or Cookstyle, or if this is a feature branch that includes multiple commits)
 
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket
 
#### Process Checks

- [ ] You have specified an "Assignee", and if necessary, additional reviewers

2022-06-28 13:46 UTC, MothOnMars submitted a review, later dismissed
A few more tweaks. After talking w/ Dan re. the I14Y README, we agreed that we should keep the language re. the services in each repo to the bare minimum, to avoid duplicating any info that's covered in the search-services README.

2022-06-28 13:46 UTC, MothOnMars commented on README.md
> +The required services (MySQL, Elasticsearch, etc.) can be run using Docker. Please refer to [searchgov-services](https://github.com/GSA/search-services) for detailed instructions on centralized confi
For consistency with `bot_detection`'s README and for simplicity, let's change this to:
```
### Services

The required services (MySQL, Elasticsearch, & Redis) can be run using Docker. Refer to [search-services](https://github.com/GSA/search-services) for detailed instructions.
```

2022-06-28 13:46 UTC, MothOnMars commented on README.md
> +Sidekiq (see below) uses [Redis](http://redis.io), so make sure you have that installed and running.
We can remove this section on Redis, as we're noting above that it is a required service, run by search-services.

2022-06-29 19:34 UTC, lorawoodford commented
Paging @danswick here too since I don't know where we stand on this element of the dev approach:

`simplify the instructions on specifying the ES_HOSTS`

Was the decision made to call out the env vars in each repo's readme (since they are differently named in each repo)?   Looks like this open PR for search-gov does call out the ES_HOSTS var in the searchgov repo's readme:  https://github.com/GSA/search-gov/pull/942/files This same language could be copy/pasted into ASIS if we're going that route.

Or, have we decided to demonstrate how to set various env vars only once in the search services repo (I checked that repo and the open PR and didn't see this)?  

Generally, this LGTM, I just want to make sure that this documentation step as requested in JIRA isn't overlooked/bypassed.

2022-07-01 18:43 UTC, lorawoodford requested changes
Alright, after meeting with @danswick we'll proceed in calling out the ES_HOSTS env var in each repo's readme.  Just add the suggested paragraph, then this will be good to go.  Thanks for your patience!

2022-07-01 18:43 UTC, lorawoodford commented on README.md
> +The required services (MySQL, Elasticsearch, & Redis) can be run using Docker. Refer to [search-services](https://github.com/GSA/search-services) for detailed instructions.
```suggestion
The required services (MySQL, Elasticsearch, & Redis) can be run using Docker. Refer to [search-services](https://github.com/GSA/search-services) for detailed instructions.

The Elasticsearch services provided by `searchgov-services` is configured to run on the default port, [9200](http://localhost:9200/). To use a different host (with or without port) or set of hosts, set the `ES_HOSTS` environment variable. For example, use following command to run the specs using Elasticsearch running on `localhost:9207`:

    ES_HOSTS=localhost:9207 bin/rspec spec
```

2022-07-05 16:07 UTC, lorawoodford approved these changes
LGTM

2022-07-08 15:54 UTC, MothOnMars requested changes

2022-07-08 15:54 UTC, MothOnMars commented on README.md
> +    ES_HOSTS=localhost:9207 bin/rspec spec
Per my comment in the ticket, this should be:
```
ES_HOSTS=localhost:9207 bundle exec rspec spec
```

2022-07-11 16:21 UTC, MothOnMars approved these changes
LGTM

2022-07-14 14:28 UTC, merged